const TILE_SIZE = 32;
const SUB_TILE_SIZE = 16;
const PLAYER_WIDTH_TILES = 1.5;
const PLAYER_HEIGHT_TILES = 2.5;
const PLAYER_CROUCH_HEIGHT_TILES = 1.5;
const PLAYER_WIDTH = TILE_SIZE * PLAYER_WIDTH_TILES;
const PLAYER_HEIGHT = TILE_SIZE * PLAYER_HEIGHT_TILES;
const PLAYER_CROUCH_HEIGHT = TILE_SIZE * PLAYER_CROUCH_HEIGHT_TILES;
const GATE_WIDTH = TILE_SIZE * 3;
const GATE_HEIGHT = TILE_SIZE * 6;

export const GAME_DATA = {
  title: {
    name: "윤회무명2",
    subtitle: "TYPE-07A Movement Lab",
    description: "움직임, HUD, 배치를 빠르게 검증하는 브라우저 프로토타입.",
  },
  art: {
    operatorStanding: {
      src: "./assets/characters/type-07a-standing.png?v=20260424-2",
    },
    playerSide: {
      src: "./assets/characters/type-07a-player-side-sd.png?v=20260424-2",
    },
    playerIdle: {
      src: "./assets/characters/type-07a-player-idle-sd.png?v=20260424-2",
    },
    playerRun: {
      src: "./assets/characters/type-07a-player-run-sd.png?v=20260424-2",
    },
    playerSprint: {
      src: "./assets/characters/type-07a-player-sprint-sd.png?v=20260424-1",
    },
    playerJump: {
      src: "./assets/characters/type-07a-player-jump-sd.png?v=20260424-2",
    },
    playerFall: {
      src: "./assets/characters/type-07a-player-fall-sd.png?v=20260424-2",
    },
    playerHoverDrone: {
      src: "./assets/characters/type-07a-player-hover-drone-sd.png?v=20260424-1",
    },
    playerDash: {
      src: "./assets/characters/type-07a-player-dash-sd.png?v=20260424-2",
    },
    playerCrouch: {
      src: "./assets/characters/type-07a-player-crouch-sd.png?v=20260424-2",
    },
    playerSlide: {
      src: "./assets/characters/type-07a-player-slide-sd.png?v=20260424-1",
    },
    playerRecoilFocus: {
      src: "./assets/characters/type-07a-player-recoil-focus-sd.png?v=20260424-1",
    },
    playerRecoilFocusUp: {
      src: "./assets/characters/type-07a-player-recoil-focus-up-sd.png?v=20260424-1",
    },
    playerRecoilFocusDown: {
      src: "./assets/characters/type-07a-player-recoil-focus-down-sd.png?v=20260424-1",
    },
    playerRecoilShot: {
      src: "./assets/characters/type-07a-player-recoil-shot-sd.png?v=20260424-1",
    },
    playerRecoilSpin: {
      src: "./assets/characters/type-07a-player-recoil-spin-sheet-sd.png?v=20260424-1",
    },
    playerWallJump: {
      src: "./assets/characters/type-07a-player-wall-jump-sd.png?v=20260424-2",
    },
    playerWallSlide: {
      src: "./assets/characters/type-07a-player-wall-slide-sd.png?v=20260424-2",
    },
    playerWallRun: {
      src: "./assets/characters/type-07a-player-wall-run-sd.png?v=20260424-2",
    },
    playerBraceHold: {
      src: "./assets/characters/type-07a-player-brace-hold-sd.png?v=20260424-2",
    },
    playerBraceRelease: {
      src: "./assets/characters/type-07a-player-brace-release-sd.png?v=20260424-2",
    },
    expeditionHudOverlay: {
      src: "./assets/ui/type07a-expedition-overlay.png",
    },
    shelterPanel: {
      src: "./assets/ui/type07a-shelter-panel.png",
    },
    titlePanel: {
      src: "./assets/ui/type07a-title-panel.png",
    },
    resultsPanel: {
      src: "./assets/ui/type07a-results-panel.png",
    },
  },
  scale: {
    tileSize: TILE_SIZE,
    subTileSize: SUB_TILE_SIZE,
    playerWidthTiles: PLAYER_WIDTH_TILES,
    playerHeightTiles: PLAYER_HEIGHT_TILES,
    crouchHeightTiles: PLAYER_CROUCH_HEIGHT_TILES,
  },
  ui: {
    themeId: "ruin-haze",
    accent: "#e7f47e",
    accentSecondary: "#93eaff",
    objectiveTitle: "목표",
    minimap: {
      enabled: true,
    },
    portraitAssetKey: "operatorStanding",
    portraitCrop: {
      sx: 250,
      sy: 70,
      sw: 520,
      sh: 520,
    },
    layout: {
      toast: { x: 52, y: 42, width: 176 },
      minimap: { x: 1148, y: 122, radius: 48 },
      objective: { x: 1062, y: 256, gap: 34 },
      status: { x: 932, y: 608, width: 156, gap: 20 },
      portrait: { x: 1168, y: 624, radius: 30 },
      actions: {
        moveX: 46,
        moveY: 648,
        dashX: 168,
        dashY: 649,
        jumpX: 44,
        jumpY: 699,
        crouchX: 126,
        crouchY: 706,
        useX: 210,
        useY: 690,
      },
      results: {
        cardX: 150,
        cardY: 104,
        cardW: 980,
        cardH: 512,
        artX: 560,
        artY: 144,
        artW: 514,
        artH: 244,
      },
    },
  },
  world: {
    mode: "movementLab",
    width: 3600,
    height: 1080,
    gravity: 2350,
    groundY: 960,
    camera: {
      zoom: 1,
      minZoom: 0.88,
      lookAheadEnabled: true,
      dashAffectsCamera: false,
      braceAffectsCamera: false,
      neutralFocusX: 0.5,
      neutralFocusY: 0.5,
      walkLookAhead: 0.08,
      sprintLookAhead: 0.18,
      sprintJumpLookAhead: 0.25,
      dashLookAhead: 0,
      wallRunLookAhead: 0,
      wallRunUpLookAhead: 0.22,
      braceLookAhead: 0,
      fallLookAhead: 0.12,
      fallDownSpeedStart: 240,
      fallDownSpeedFull: 1120,
      fallDownFocusStartY: 0.42,
      fallDownFocusFullY: 0.31,
      fallZoom: 0.9,
      fallSpeedZoomMultiplier: 0.55,
      fallReturnHoldMs: 240,
      fallFocusLerp: 8.5,
      fallReturnLerp: 3.6,
      fallLandingProbeDistance: 620,
      fallLandingProbeMaxTime: 0.72,
      fallLandingCameraPull: 0.22,
      fallLandingCameraMaxOffset: 150,
      directionSpeedThreshold: 70,
      sprintCameraMinSpeed: 260,
      speedZoomStart: 260,
      speedZoomFull: 980,
      speedZoomMin: 0.88,
      upwardFocusOffset: 0.18,
      fallingFocusOffset: -0.14,
      sprintZoom: 0.96,
      sprintJumpZoom: 0.92,
      dashZoom: 1,
      wallRunZoom: 0.94,
      braceZoom: 1,
      directionLerp: 6,
      focusLerp: 5.5,
      zoomLerp: 4.2,
    },
    duskAt: 9999,
    nightAt: 19999,
    sanityDrain: {
      day: 0,
      dusk: 0,
      night: 0,
    },
    startMessage: "이동 실험실 진입.",
    startClueLog: [
      "플랫폼 간격과 벽 높이를 먼저 본다.",
      "스프라이트 비율은 에디터에서 바로 조정할 수 있다.",
      "출구까지 도달하면 결과 화면으로 넘어간다.",
    ],
    labObjectives: [
      "달리기 감각 확인",
      "점프와 버퍼 확인",
      "벽 슬라이드 확인",
      "대시 거리 확인",
      "출구까지 도달",
    ],
  },
  player: {
    spawn: { x: 176, y: 880 },
    size: { width: PLAYER_WIDTH, height: PLAYER_HEIGHT },
    speed: 360,
    jumpVelocity: -900,
    maxHp: 100,
    maxSanity: 100,
    maxBattery: 100,
    startingSanity: 100,
    attackDamage: 34,
    attackCooldown: 0.42,
    lightDrainPerSecond: 10,
    movement: {
      runSpeed: 440,
      sprintSpeed: 680,
      sprintBuildMs: 520,
      sprintDecayMs: 220,
      sprintJumpCarryMs: 360,
      sprintJumpMinSpeed: 760,
      slideMinSpeed: 420,
      slideDurationMs: 520,
      slideFriction: 260,
      slideSpeedMultiplier: 1.04,
      slideJumpCarryMs: 420,
      slideJumpMinSpeed: 780,
      slideJumpSpeedMultiplier: 1.14,
      hoverFallSpeed: 150,
      hoverGravityMultiplier: 0.16,
      hoverStartMaxFallSpeed: 220,
      hoverStartMinVy: -60,
      hoverAirControlMultiplier: 0.9,
      groundAccel: 3400,
      groundDecel: 4200,
      airControlMultiplier: 0.75,
      jumpVelocity: -930,
      coyoteTimeMs: 100,
      jumpBufferMs: 120,
      jumpCutMultiplier: 0.45,
      apexGravityMultiplier: 0.58,
      apexGravityThreshold: 180,
      jumpCornerCorrectionPx: 12,
      dashDurationMs: 120,
      dashDistance: 98,
      maxDashCount: 1,
      dashCooldownMs: 450,
      dashCornerCorrectionPx: 12,
      dashCarryWindowMs: 150,
      dashCarrySpeedMultiplier: 0.68,
      dashJumpMinSpeed: 520,
      dashInvulnerable: true,
      crouchHeight: PLAYER_CROUCH_HEIGHT,
      crouchSpeedMultiplier: 0.45,
      wallSlideFallMultiplier: 0.4,
      wallCoyoteTimeMs: 110,
      wallSlideGraceMs: 80,
      wallSpeedRetentionMs: 90,
      wallSpeedRetentionMinSpeed: 180,
      wallRunStartSpeed: 260,
      wallRunAccel: 1680,
      wallRunMaxSpeed: 920,
      wallRunExitMinBoost: 720,
      wallRunExitHorizontal: 180,
      wallJumpHorizontal: 506,
      wallJumpVertical: 840,
      wallJumpLockMs: 100,
      braceDetectPaddingX: 24,
      braceDetectPaddingY: 24,
      braceHoldStartSpeed: 24,
      braceHoldAccel: 360,
      braceHoldFallSpeed: 220,
      braceHoldMoveMultiplier: 0.72,
      braceBoostHorizontal: 560,
      braceBoostVertical: 940,
      braceReuseMs: 180,
      recoilShotCharges: 1,
      recoilShotForce: 840,
      recoilShotMaxHorizontalSpeed: 1180,
      recoilShotMaxUpSpeed: 1180,
      recoilShotMaxFallSpeed: 760,
      recoilShotCooldownMs: 180,
      recoilShotFocusTimeScale: 0.22,
      recoilShotAimLookAhead: 0.1,
      recoilShotAimUpLookAhead: 0.14,
      recoilShotRecoilLookAhead: 0.18,
      recoilShotRecoilUpLookAhead: 0.2,
      recoilShotCameraHoldMs: 240,
      recoilSpinDurationMs: 220,
      recoilSpinLoopCount: 2,
      recoilAimVerticalPoseThreshold: 0.45,
    },
    render: {
      idleAssetKey: "playerIdle",
      runAssetKey: "playerRun",
      sprintAssetKey: "playerSprint",
      jumpAssetKey: "playerJump",
      fallAssetKey: "playerFall",
      hoverAssetKey: "playerHoverDrone",
      dashAssetKey: "playerDash",
      crouchAssetKey: "playerCrouch",
      slideAssetKey: "playerSlide",
      recoilFocusAssetKey: "playerRecoilFocus",
      recoilFocusUpAssetKey: "playerRecoilFocusUp",
      recoilFocusDownAssetKey: "playerRecoilFocusDown",
      recoilShotAssetKey: "playerRecoilShot",
      recoilSpinAssetKey: "playerRecoilSpin",
      wallJumpAssetKey: "playerWallJump",
      wallSlideAssetKey: "playerWallSlide",
      wallRunAssetKey: "playerWallRun",
      braceHoldAssetKey: "playerBraceHold",
      braceReleaseAssetKey: "playerBraceRelease",
      fallbackAssetKey: "playerSide",
      widthRatio: 1,
      heightRatio: 1.52,
      idleWidthRatio: 1,
      idleHeightRatio: 1.52,
      runWidthRatio: 1,
      runHeightRatio: 1.52,
      sprintWidthRatio: 1,
      sprintHeightRatio: 1.48,
      jumpWidthRatio: 1,
      jumpHeightRatio: 1.52,
      fallWidthRatio: 1,
      fallHeightRatio: 1.52,
      hoverWidthRatio: 1,
      hoverHeightRatio: 1.92,
      hoverSourceFacing: 1,
      dashWidthRatio: 1,
      dashHeightRatio: 1.44,
      crouchWidthRatio: 1,
      crouchHeightRatio: 1.18,
      slideWidthRatio: 1.12,
      slideHeightRatio: 1.32,
      recoilFocusWidthRatio: 1.08,
      recoilFocusHeightRatio: 1.48,
      recoilFocusUpWidthRatio: 1.08,
      recoilFocusUpHeightRatio: 1.48,
      recoilFocusDownWidthRatio: 1.08,
      recoilFocusDownHeightRatio: 1.48,
      recoilShotWidthRatio: 1.08,
      recoilShotHeightRatio: 1.48,
      recoilSpinWidthRatio: 1,
      recoilSpinHeightRatio: 1.9,
      recoilSpinFrameCount: 4,
      recoilSpinLoopCount: 2,
      recoilSpinSourceFacing: 1,
      wallJumpWidthRatio: 1,
      wallJumpHeightRatio: 1.56,
      wallSlideWidthRatio: 1,
      wallSlideHeightRatio: 1.5,
      wallRunWidthRatio: 1,
      wallRunHeightRatio: 1.56,
      braceHoldWidthRatio: 1,
      braceHoldHeightRatio: 1.5,
      braceReleaseWidthRatio: 1,
      braceReleaseHeightRatio: 1.56,
      idleAnchorX: 0.29,
      runAnchorX: 0.17,
      sprintAnchorX: 0.18,
      jumpAnchorX: 0.48,
      fallAnchorX: 0.46,
      hoverAnchorX: 0.48,
      hoverFootAnchorY: 0.88,
      dashAnchorX: 0.34,
      crouchAnchorX: 0.48,
      slideAnchorX: 0.36,
      recoilFocusAnchorX: 0.34,
      recoilFocusUpAnchorX: 0.34,
      recoilFocusDownAnchorX: 0.34,
      recoilShotAnchorX: 0.34,
      recoilSpinAnchorX: 0.5,
      recoilSpinFootAnchorY: 0.8,
      wallJumpAnchorX: 0.34,
      wallSlideAnchorX: 0.38,
      wallRunAnchorX: 0.34,
      braceHoldAnchorX: 0.38,
      braceReleaseAnchorX: 0.34,
      footAnchorY: 0.978,
    },
  },
  extractionGate: {
    x: 3440,
    y: 768,
    width: GATE_WIDTH,
    height: GATE_HEIGHT,
    prompt: "E: 추출",
  },
  platforms: [
    { x: 0, y: 960, width: 760, height: 120, color: "#2f3b47" },
    { x: 920, y: 960, width: 520, height: 120, color: "#35424f" },
    { x: 1560, y: 960, width: 560, height: 120, color: "#2b3845" },
    { x: 2280, y: 960, width: 520, height: 120, color: "#313f4d" },
    { x: 2960, y: 960, width: 640, height: 120, color: "#334351" },
    { x: 980, y: 888, width: 220, height: 20, color: "#445668" },
    { x: 620, y: 836, width: 100, height: 22, color: "#53677a" },
    { x: 1010, y: 840, width: 180, height: 24, color: "#5d7286" },
    { x: 1250, y: 760, width: 170, height: 24, color: "#6a8093" },
    { x: 1560, y: 824, width: 120, height: 20, color: "#54697b" },
    { x: 1648, y: 760, width: 36, height: 200, color: "#445769" },
    { x: 1876, y: 760, width: 36, height: 200, color: "#4a6073" },
    { x: 1690, y: 668, width: 178, height: 22, color: "#5b7084" },
    { x: 1892, y: 812, width: 132, height: 20, color: "#5a6f81" },
    { x: 2350, y: 824, width: 120, height: 22, color: "#62788b" },
    { x: 2548, y: 744, width: 120, height: 22, color: "#70869a" },
    { x: 2746, y: 664, width: 120, height: 22, color: "#7d94a7" },
    { x: 3040, y: 852, width: 180, height: 20, color: "#55697c" },
    { x: 3260, y: 760, width: 36, height: 200, color: "#4f6476" },
    { x: 3292, y: 672, width: 132, height: 22, color: "#607587" },
  ],
  props: [
    { kind: "sign", x: 220, y: 908, text: "달리기" },
    { kind: "sign", x: 474, y: 908, text: "앉기" },
    { kind: "sign", x: 1060, y: 908, text: "점프" },
    { kind: "sign", x: 1776, y: 908, text: "벽" },
    { kind: "sign", x: 2578, y: 908, text: "대시" },
    { kind: "sign", x: 3382, y: 908, text: "출구" },
    { kind: "lantern", x: 244, y: 916 },
    { kind: "lantern", x: 1034, y: 916 },
    { kind: "lantern", x: 1758, y: 916 },
    { kind: "lantern", x: 2568, y: 916 },
    { kind: "lantern", x: 3380, y: 916 },
  ],
  braceWalls: [
    { id: "brace-1", x: 1464, y: 664, width: 44, height: 208 },
    { id: "brace-2", x: 2488, y: 612, width: 44, height: 184 },
    { id: "brace-3", x: 3188, y: 690, width: 44, height: 188 },
  ],
  interactables: [],
  encounters: [
    {
      id: "guard",
      disabled: true,
      label: "경비형",
      identity: "규칙 감시자",
      type: "guard",
      x: -400,
      y: -400,
      width: 46,
      height: 82,
      patrol: { left: -400, right: -400 },
      checkpointZone: { x: -420, y: -420, width: 10, height: 10 },
      detectionRadius: 0,
      speed: 0,
      chaseSpeed: 0,
      attackRange: 0,
      damage: 0,
      maxHp: 1,
      harvestReward: 0,
      harvestSanityCost: 0,
      releaseSanity: 0,
      storyFlag: "guard-ledger",
      storyText: "",
      clues: {
        motion: "",
        badge: "",
        still: "",
      },
    },
    {
      id: "ritualist",
      disabled: true,
      label: "의식형",
      identity: "순서 집착체",
      type: "ritualist",
      x: -500,
      y: -500,
      width: 48,
      height: 88,
      ritualArea: { x: -520, y: -520, width: 10, height: 10 },
      patrolPoints: [
        { x: -500, y: -500 },
      ],
      pedestals: [],
      correctOrder: [],
      speed: 0,
      chaseSpeed: 0,
      attackRange: 0,
      damage: 0,
      maxHp: 1,
      harvestReward: 0,
      harvestSanityCost: 0,
      releaseSanity: 0,
      storyFlag: "ritual-map",
      storyText: "",
      clues: {
        area: "",
        wrong: "",
        light: "",
      },
    },
  ],
  nightThreats: [],
  abilityDefs: {
    threatSense: {
      id: "threatSense",
      name: "위협 감지",
      description: "Q 입력 시 위협과 핵심 단서를 강조한다.",
    },
  },
  shelterNpc: {
    name: "Type-07A",
    role: "오퍼레이터",
    dialogue: "움직임과 화면 배치를 필요한 만큼만 조정한다.",
  },
};
